package utils

import "time"

type BoletoCodeType string

type BoletoType string

const BaseDate = "1997-10-07 00:00:00"

type Boleto struct {
	IssuerBankCode    string
	IssuerBankName    string
	Currency          int
	IssuerReserved1   string
	CheckDigit1       int
	IssuerReserved2   string
	CheckDigit2       int
	IssuerReserved3   string
	CheckDigit3       int
	GeneralCheckDigit int
	DueDate           time.Time
	Amount            float64
	CodeType          BoletoCodeType
}

var Banks = map[string]string{
	"001": "Banco do Brasil S.A.",
	"003": "Banco da Amazônia S.A.",
	"004": "Banco do Nordeste do Brasil S.A.",
	"007": "Banco Nacional de Desenvolvimento Econômico e Social",
	"010": "Credicoamo Crédito Rural Cooperativa",
	"011": "Credit Suisse Hedging-Griffo Corretora de Valores S.A.",
	"012": "Banco Inbursa S.A.",
	"014": "State Street Brasil S.A. - Banco Comercial",
	"015": "UBS Brasil Corretora de Câmbio Títulos e Valores Mobiliários S.A.",
	"016": "Cooperativa de Crédito Mútuo dos Despachantes de Trânsito de Santa Catarina e Ri",
	"017": "BNY Mellon Banco S.A.",
	"018": "Banco Tricury S.A.",
	"021": "Banestes S.A. Banco do Estado do Espírito Santo",
	"024": "Banco Bandepe S.A.",
	"025": "Banco Alfa S.A.",
	"029": "Banco Itaú Consignado S.A.",
	"033": "Banco Santander (Brasil) S.A.",
	"036": "Banco Bradesco BBI S.A.",
	"037": "Banco do Estado do Pará S.A.",
	"040": "Banco Cargill S.A.",
	"041": "Banco do Estado do Rio Grande do Sul S.A.",
	"047": "Banco do Estado de Sergipe S.A.",
	"060": "Confidence Corretora de Câmbio S.A.",
	"062": "Hipercard Banco Múltiplo S.A.",
	"063": "Banco Bradescard S.A.",
	"064": "Goldman Sachs do Brasil Banco Múltiplo S.A.",
	"065": "Banco AndBank (Brasil) S.A.",
	"066": "Banco Morgan Stanley S.A.",
	"069": "Banco Crefisa S.A.",
	"070": "BRB - Banco de Brasília S.A.",
	"074": "Banco J. Safra S.A.",
	"075": "Banco ABN Amro S.A.",
	"076": "Banco KDB do Brasil S.A.",
	"077": "Banco Inter S.A.",
	"078": "Haitong Banco de Investimento do Brasil S.A.",
	"079": "Picpay Bank - Banco Múltiplo S.A.",
	"080": "B&T Corretora de Câmbio Ltda.",
	"081": "Bancoseguro S.A.",
	"082": "Banco Topázio S.A.",
	"083": "Banco da China Brasil S.A.",
	"084": "Uniprime do Brasil - Cooperativa de Crédito",
	"085": "Cooperativa Central de Crédito - Ailos",
	"088": "Banco Randon S.A.",
	"089": "Credisan Cooperativa de Crédito",
	"091": "Central de Cooperativas de Economia e Crédito Mútuo do Estado do Rio Grande do S",
	"092": "BRK S.A. Crédito Financiamento e Investimento",
	"093": "Pólocred Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Port",
	"094": "Banco Finaxis S.A.",
	"095": "Travelex Banco de Câmbio S.A.",
	"096": "Banco B3 S.A.",
	"097": "Credisis - Central de Cooperativas de Crédito Ltda.",
	"098": "Credialiança Cooperativa de Crédito Rural",
	"099": "Uniprime Central Nacional - Central Nacional de Cooperativa de Crédito",
	"100": "Planner Corretora de Valores S.A.",
	"101": "Renascença Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"102": "XP Investimentos Corretora de Câmbio Títulos e Valores Mobiliários S/A",
	"104": "Caixa Econômica Federal",
	"105": "Lecca Crédito Financiamento e Investimento S/A",
	"107": "Banco Bocom BBM S.A.",
	"108": "Portocred S.A. - Crédito Financiamento e Investimento",
	"111": "Oliveira Trust Distribuidora de Títulos e Valores Mobiliários S.A.",
	"113": "Neon Corretora de Títulos e Valores Mobiliários S.A.",
	"114": "Central Cooperativa de Crédito no Estado do Espírito Santo - Cecoob",
	"117": "Advanced Corretora de Câmbio Ltda.",
	"119": "Banco Western Union do Brasil S.A.",
	"120": "Banco Rodobens S.A.",
	"121": "Banco Agibank S.A.",
	"122": "Banco Bradesco Berj S.A.",
	"124": "Banco Woori Bank do Brasil S.A.",
	"125": "Banco Genial S.A.",
	"126": "BR Partners Banco de Investimento S.A.",
	"127": "Codepe Corretora de Valores e Câmbio S.A.",
	"128": "MS Bank S.A. Banco de Câmbio",
	"129": "UBS Brasil Banco de Investimento S.A.",
	"130": "Caruana S.A. - Sociedade de Crédito Financiamento e Investimento",
	"131": "Tullett Prebon Brasil Corretora de Valores e Câmbio Ltda.",
	"132": "ICBC do Brasil Banco Múltiplo S.A.",
	"133": "Confederação Nacional das Cooperativas Centrais de Crédito e Economia Familiar e",
	"134": "BGC Liquidez Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"136": "Confederação Nacional das Cooperativas Centrais Unicred Ltda. - Unicred do Brasi",
	"138": "Get Money Corretora de Câmbio S.A.",
	"139": "Intesa Sanpaolo Brasil S.A. - Banco Múltiplo",
	"140": "Nu Invest Corretora de Valores S.A.",
	"142": "Broker Brasil Corretora de Câmbio Ltda.",
	"143": "Treviso Corretora de Câmbio S.A.",
	"144": "Bexs Banco de Câmbio S/A",
	"145": "Levycam - Corretora de Câmbio e Valores Ltda.",
	"146": "Guitta Corretora de Câmbio Ltda.",
	"149": "Facta Financeira S.A. - Crédito Financiamento e Investimento",
	"157": "ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.",
	"159": "Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor",
	"163": "Commerzbank Brasil S.A. - Banco Múltiplo",
	"172": "Albatross Ccv S.A",
	"173": "BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.",
	"174": "Pefisa S.A. - Crédito Financiamento e Investimento",
	"177": "Guide Investimentos S.A. Corretora de Valores",
	"180": "CM Capital Markets Corretora de Câmbio Títulos e Valores Mobiliários Ltda.",
	"183": "Socred S.A. - Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno P",
	"184": "Banco Itaú BBA S.A.",
	"188": "Ativa Investimentos S.A. Corretora de Títulos Câmbio e Valores",
	"189": "HS Financeira S/A Crédito Financiamento e Investimentos",
	"190": "Servicoop - Cooperativa de Crédito dos Servidores Públicos Estaduais e Municipai",
	"191": "Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.",
	"194": "Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"195": "Valor Sociedade de Crédito Direto S.A.",
	"196": "Fair Corretora de Câmbio S.A.",
	"197": "Stone Instituição de Pagamento S.A.",
	"204": "Banco Bradesco Cartões S.A.",
	"208": "Banco BTG Pactual S.A.",
	"212": "Banco Original S.A.",
	"213": "Banco Arbi S.A.",
	"217": "Banco John Deere S.A.",
	"218": "Banco BS2 S.A.",
	"222": "Banco Crédit Agricole Brasil S.A.",
	"224": "Banco Fibra S.A.",
	"233": "Banco Cifra S.A.",
	"237": "Banco Bradesco S.A.",
	"241": "Banco Clássico S.A.",
	"243": "Banco Master S/A",
	"246": "Banco ABC Brasil S.A.",
	"249": "Banco Investcred Unibanco S.A.",
	"250": "BCV - Banco de Crédito e Varejo S.A.",
	"253": "Bexs Corretora de Câmbio S/A",
	"254": "Paraná Banco S.A.",
	"259": "Moneycorp Banco de Câmbio S.A.",
	"260": "Nu Pagamentos S.A. - Instituição de Pagamento",
	"265": "Banco Fator S.A.",
	"266": "Banco Cédula S.A.",
	"268": "Bari Companhia Hipotecária",
	"269": "Banco HSBC S.A.",
	"270": "Sagitur Corretora de Câmbio Ltda.",
	"271": "IB Corretora de Câmbio, Títulos e Valores Mobiliários Ltda.",
	"272": "AGK Corretora de Câmbio S.A.",
	"273": "Cooperativa de Crédito Rural de São Miguel do Oeste - Sulcredi/São Miguel",
	"274": "Mirae Asset Wealth Management (Brasil) Corretora de Câmbio e Valores Mobiliários",
	"276": "Senff S.A. - Crédito Financiamento e Investimento",
	"278": "Genial Investimentos Corretora de Valores Mobiliários S.A.",
	"279": "Cooperativa de Crédito Rural de Primavera do Leste",
	"280": "Avista S.A. - Crédito Financiamento e Investimento",
	"281": "Cooperativa de Crédito Rural Coopavel",
	"283": "RB Capital Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"285": "Frente Corretora de Câmbio Ltda.",
	"286": "Cooperativa de Crédito Rural de Ouro - Sulcredi/Ouro",
	"288": "Carol Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"289": "Decyseo Corretora de Câmbio Ltda.",
	"290": "Pagseguro Internet S.A.",
	"292": "BS2 Distribuidora de Títulos e Valores Mobiliários S.A.",
	"293": "Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"294": "F.D'Gold Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"295": "OZ Corretora de Câmbio S.A.",
	"298": "Vip's Corretora de Câmbio Ltda.",
	"299": "Sorocred Crédito, Financiamento e Investimento S.A.",
	"300": "Banco de la Nacion Argentina",
	"301": "BPP Instituição de Pagamento S.A.",
	"306": "Portopar Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"307": "Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"309": "Cambionet Corretora de Câmbio Ltda.",
	"310": "Vortx Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"313": "Amazônia Corretora de Câmbia Ltda.",
	"318": "Banco BMG S.A.",
	"319": "OM Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"320": "China Construction Bank (Brasil) Banco Múltiplo S.A.",
	"321": "Credisitrus - Cooperativa de Crédito Rural",
	"322": "Cooperativa de Crédito de Livre Admissão de Associados do Alto Uruguai",
	"323": "Mercado Pago - Instituição de Pagamento Ltda.",
	"324": "C6 S.A. - Crédito, Financiamento e Investimento",
	"325": "Órama Distribuidora de Títulos e Valores Mobiliários S.A.",
	"326": "Parati - Crédito Financiamento e Investimento S.A.",
	"329": "Avenue Securities Corretora de Valores Mobiliários S.A.",
	"330": "Banco Bari de Investimentos e Financiamentos S.A.",
	"331": "Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.",
	"332": "Acesso Soluções de Pagamento S.A.",
	"335": "Banco Digio S.A.",
	"336": "Banco C6 S.A.",
	"340": "Super Pagamentos e Administração de Meios Eletrônicos Ltda.",
	"341": "Itaú Unibanco S.A.",
	"342": "Creditas Sociedade de Crédito Direto S.A.",
	"343": "FFA Distribuidora de Títulos e Valores Mobiliários Ltda.",
	"348": "Banco XP S.A.",
	"349": "Amaggi S.A. Crédito Financiamento e Investimento",
	"352": "Toro Corretora de Títulos e Valores Mobiliários Ltda.",
	"355": "Ótimo Sociedade de Crédito Direto S.A.",
	"359": "Zema Crédito Financiamento e Investimento S/A",
	"360": "Trinus Co Sociedade de Crédito Direto S.A.",
	"364": "Geru Tecnologia e Serviços S.A.",
	"365": "Socinal S.A. - Crédito, Financiamento e Investimento",
	"366": "Banco Société Générale Brasil S.A.",
	"368": "Banco CSF S.A.",
	"370": "Banco Mizuho do Brasil S.A.",
	"371": "Banco Volkswagen S.A.",
	"373": "Up.p Sociedade de Empréstimo Entre Pessoas S.A.",
	"376": "Banco J.P. Morgan S.A.",
	"378": "Banco Bradesco Europa S.A.",
	"379": "Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz",
	"380": "PicPay",
	"381": "Banco Mercedes-Benz do Brasil S.A.",
	"382": "FIDUC S.A. - Crédito Financiamento e Investimento",
	"383": "Fiat Automóveis S.A.",
	"384": "Rondocred Cooperativa de Crédito de Livre Admissão",
	"385": "Banco Toyota do Brasil S.A.",
	"386": "Cooperativa de Crédito Rural de Iomerê - Credirio",
	"387": "Banco CNH Industrial Capital S.A.",
	"389": "Banco Mercantil do Brasil S.A.",
	"390": "Cooperativa de Crédito Rural de Livre Admissão de São Roque do Canaã",
	"392": "Banco Mercantil de Investimentos S.A.",
	"393": "Banco Volkswagen S.A.",
	"394": "Banco Bradesco Financiamentos S.A.",
	"395": "F.D'Gold Corretora de Câmbio Ltda.",
	"396": "HUB Pagamentos S.A.",
	"399": "Kirton Bank S.A. - Banco Múltiplo",
	"406": "Accredito - Sociedade de Crédito Direto S.A.",
	"412": "Banco Capital S.A.",
	"413": "Banco BV S.A.",
	"422": "Banco Safra S.A.",
	"456": "Banco MUFG Brasil S.A.",
	"461": "Asaas",
	"464": "Banco Sumitomo Mitsui Brasileiro S.A.",
	"473": "Banco Caixa Geral - Brasil S.A.",
	"477": "Citibank N.A.",
	"479": "Banco ItauBank S.A.",
	"481": "Superlógica Sociedade de Crédito Direto S.A.",
	"487": "Deutsche Bank S.A. - Banco Alemão",
	"488": "JPMorgan Chase Bank, National Association",
	"492": "ING Bank N.V.",
	"494": "Banco de La Republica Oriental del Uruguay",
	"495": "La Provincia Buenos Aires Banco de La",
	"505": "Banco Credit Suisse (Brasil) S.A.",
	"545": "Senso Corretora de Câmbio e Valores Mobiliários S.A.",
	"600": "Banco Luso Brasileiro S.A.",
	"604": "Banco Industrial do Brasil S.A.",
	"610": "Banco VR S.A.",
	"611": "Banco Paulista S.A.",
	"612": "Banco Guanabara S.A.",
	"613": "Omni Banco S.A.",
	"623": "Banco Pan S.A.",
	"626": "Banco Ficsa S.A.",
	"630": "Banco Smartbank S.A.",
	"633": "Banco Rendimento S.A.",
	"634": "Banco Triângulo S.A.",
	"637": "Banco Sofisa S.A.",
	"641": "Banco Alvorada S.A.",
	"643": "Banco Pine S.A.",
	"652": "Itaú Unibanco Holding S.A.",
	"653": "Banco Indusval S.A.",
	"654": "Banco A.J. Renner S.A.",
	"655": "Banco Votorantim S.A.",
	"707": "Banco Daycoval S.A.",
	"712": "Banco Ourinvest S.A.",
	"719": "Banif - Bco Internacional do Funchal (Brasil) S.A.",
	"720": "Banco Maxinvest S.A.",
	"735": "Banco Neon S.A.",
	"739": "Banco Cetelem S.A.",
	"741": "Banco Ribeirão Preto S.A.",
	"743": "Banco Semear S.A.",
	"745": "Banco Citibank S.A.",
	"746": "Banco Modal S.A.",
	"747": "Banco Rabobank International Brasil S.A.",
	"748": "Banco Cooperativo Sicredi S.A.",
	"751": "Scotiabank Brasil S.A. Banco Múltiplo",
	"752": "Banco BNP Paribas Brasil S.A.",
	"753": "Novo Banco Continental S.A. - Banco Múltiplo",
	"754": "Banco Sistema S.A.",
	"755": "Bank of America Merrill Lynch Banco Múltiplo S.A.",
	"756": "Banco Cooperativo do Brasil S.A. - Bancoob",
	"757": "Banco Keb Hana do Brasil S.A.",
}
